environment:
  version: 1.0.0
  matrix:
    - node: "8"
install:
  - ps: Install-Product node $env:node
assembly_info:
  patch: false
build_script:
  build.cmd publish
test: off
image: Visual Studio 2017
