environment:
  version: 1.0.0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
assembly_info:
  patch: false
branches:
  except:
  - master
services:
  - mssql2017
build_script:
  build.cmd --target Build-docker-image
test: off
image: Visual Studio 2022