install:
  - ps: Install-Product node 1
environment:
  version: 1.0.0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
assembly_info:
  patch: false
branches:
  only:
  - master
services:
  - mssql2017
build_script:
  ./build.sh
test: off
image: Ubuntu2004