environment:
  version: 1.0.0
  matrix:
    - node: "8"
install:
  - ps: Install-Product node $env:node
  - cmd: dotnet tool install fake-cli -g --version 5.10.1
assembly_info:
  patch: false
branches:
  only:
  - master
services:
  - mssql2017
build_script:
  build.cmd
test: off
image: Visual Studio 2017
