environment:
  version: 1.0.0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  matrix:
  - nodejs_version: "16"
assembly_info:
  patch: false
branches:
  only:
  - master
services:
  - mssql2017
build_script:
  ./build.sh
test: off
image: Ubuntu2004