environment:
  version: 1.0.0
  matrix:
    - node: "8"
install:
  - ps: Install-Product node $env:node
assembly_info:
  patch: false
branches:
  only:
  - production
build_script:
  build.cmd
test: off
image: Visual Studio 2017