environment:
  version: 1.0.0
  matrix:
    - node: "8"
install:
  - ps: Install-Product node $env:node
assembly_info:
  patch: false
branches:
  except:
  - master
services:
  - mssql2017

build_script:
  build.cmd --target Create-Artifact
test: off
image: Visual Studio 2017
