steps:
- id: 'restore tools'
  name: mcr.microsoft.com/dotnet/sdk:6.0
  entrypoint: dotnet
  args: ['tool', 'restore']

- id: 'run fake script'
  waitFor: ['restore tools']
  name: mcr.microsoft.com/dotnet/sdk:6.0
  entrypoint: dotnet
  args: ['fake', 'run', 'build.fsx', '--parallel', '3']

options:
  env:
    - 'DOTNET_CLI_TELEMETRY_OPTOUT=true'
    - 'NUGET_XMLDOC_MODE=skip'
timeout: 900s
