name: Build
on: 
  push:
     branches:
      - master

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x'
    - run: ./build.sh