name: CI
on: 
  push:
     branches:
      - '*'
      - '*/**/*'
      - '!master'

jobs:
  build-frontend:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x'
    - run: ./build.sh --target Publish